name: little_dino_app
version: 1.0.1+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5


  http: ^0.13.5

# <---------------------- Toast ------------------------>
  fluttertoast: ^8.1.1

# <---------------------- Animated Progress Button ------------------------>
  rounded_loading_button: ^2.1.0

# <---------------------- Animation on On_Boarding Screen ------------------------>
  liquid_swipe: ^3.0.0

#  <----------------- manage screen size either font size,width or height ------------------>
  flutter_screenutil: 5.5.3+2

#  <----------------------- Bottom navigation bar -------------------------->
  curved_navigation_bar: 1.0.3

#  <----------------- Svg Image ----------------------->
  flutter_svg: 1.1.2

#  <--------------------- swap card in detail sacreen of categories ----------->
  flutter_carousel_widget: 1.1.0

#  <---------------- scroll index ----------------->
  scroll_to_index: 3.0.1

#  <---------- for solve error it's not complusury -------------->
#  assets_audio_player: 3.0.5
#  audioplayers: 1.0.1
#  audio_service: 0.18.7

#  <----------------- Play Only audio --------------->
#  audio_session: 0.1.10
  just_audio: 0.9.28

#  <-------------------------- hexcolor convert to Color ----------------->
  hexcolor: 2.0.7

#  <---------------- firebase Intigration -------------->
  flutter_login_facebook: ^1.6.0
  firebase_core: 1.20.1
  firebase_auth: 3.4.1
  cloud_firestore: ^3.4.6
  google_sign_in: ^5.4.1
  firebase_analytics: ^9.3.8

  #  <------------------------- Firebase In App Messaging ---------------->
  firebase_in_app_messaging: ^0.6.0+27
  firebase_messaging: ^13.1.0


  flutter_facebook_auth: ^4.4.1

  #-----------------> Flutter Talk To Speech <-----------------
  flutter_tts: ^3.5.1

#  <---------------- drawer -------------->
  flutter_advanced_drawer: ^1.3.2

# <---------------- indicator -------------->
  percent_indicator: ^4.2.2

# <----------------  swip careds -------------->
  flutter_swipecards: ^0.2.1

#  <----------------- Design Redio ---------------->
  custom_radio_grouped_button: ^2.1.2+2

#  <-----------------  TabBar of My Save ---------------->
  animated_segmented_tab_control: ^1.0.1

#  <------------------------ Change Date Time Formate--------------->
  intl: ^0.17.0

#  <--------------------- Pick Images ------------------------>
  image_picker: ^0.8.5+3

#  <------------------------ Laocal data Manage --------------------->
  hive: ^2.2.3
  hive_flutter: ^1.1.0

#  <-------------------- OTP ------------------------>
  pin_code_fields: ^7.4.0

#<---------------- Disable Screenshote --------------->
  flutter_windowmanager: ^0.2.0

#<------------------------ Cach NetworkImagies -------------------->
  cached_network_image: ^3.2.1


dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

#  < ------------------- manage data Localy ---------------------->
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

  #<------------------- Change Icon --------------------->
  flutter_launcher_icons: ^0.10.0

 # <------------------- Email Authentication ---------------->
  email_auth: ^1.0.0

#  <------------------------- On Complete Screen ---------------->
  confetti: ^0.7.0


flutter_icons:
  image_path: "assets/login/ligo.png"
  android: true
  ios: true


flutter: 
  assets: 
    - assets/
    - assets/bottomnavigationBar/
    - assets/appbar/
    - assets/categorys/
    - assets/detail_bottomnavigationbar/
    - assets/models/
    - assets/login/
    - assets/drawer/
    - assets/level/
    - assets/result/
    - assets/onboarding/
    - assets/onboarding/Onboarding_1/
    - assets/onboarding/onboarding_2/
    - assets/onboarding/onboarding_3/
    - assets/Home/
    - assets/homePage/
    - assets/drawer/
    - assets/level/
    - assets/profile/
    - assets/forgatePassword/

  fonts:
    - family: Dosis
      fonts: 
        - asset: fonts/Dosis-ExtraLight.ttf
          weight: 300
        - asset: fonts/Dosis-Light.ttf
          weight: 400
        - asset: fonts/Dosis-Regular.ttf
          weight: 500
        - asset: fonts/Dosis-Medium.ttf
          weight: 600
        - asset: fonts/Dosis-SemiBold.ttf
          weight: 700
        - asset: fonts/Dosis-Bold.ttf
          weight: 800
  uses-material-design: true

